from arango import ArangoClient
import base64

encodedCA = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHRENDQWdDZ0F3SUJBZ0lRR1N1UDR1TkI1YXhoczdQU2paTUxCakFOQmdrcWhraUc5dzBCQVFzRkFEQW0KTVJFd0R3WURWUVFLRXdoQmNtRnVaMjlFUWpFUk1BOEdBMVVFQXhNSVFYSmhibWR2UkVJd0hoY05NalF3TnpJMApNREl5TkRFMFdoY05Namt3TnpJek1ESXlOREUwV2pBbU1SRXdEd1lEVlFRS0V3aEJjbUZ1WjI5RVFqRVJNQThHCkExVUVBeE1JUVhKaGJtZHZSRUl3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzIKRzJhQmFUbytJTTY5MTVEMEMwNGVJS2U3anBnUi9oLzBoYVhueHlxMm5YemhkV29vUFRuQXB2d29QTU5xc2R2KwpWRWhYRGpHVytVZDlBZUxHRkZFQnZieHdLcTdYZ3NZYTVUMi9aWjBrRlgrZVdhODlVT2xQMVZka3QwTFZRRXFUCnFJQnJhRVF4Y0p4TWp2Tzc4bzd1WHFwcWdBbWsvRnNCRHpzNEVDT3VUK0hVUElJOGlIUzZiYTFyeUs1WCt3S2wKQU0xQWtEckRLbmI1c2ZwdEl4RDRjb3d1Z3hpbXZVMEdsME15eitXNThWYlpHdzJDZG1KVCtqc3IwV2h5R0k1dQo1TXRZNVMwZ3EwK3QxQWh6aktmQ21MNXZIV1BoZVBGVExnM1hnWkJGNks2ZklmaUdNZlJlL2dtRG1lUEJIaWJDCkVkajZ5MTQrdzR0dlZNR3h6Q2NsQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRaHFIQ3I5b3VTUFpLaWJVUG9Rc2RBVHJGcHBEQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBZFcvTHIrSXJsYTlFam02UWhwK1NhdTZLM0xiclhqY3pMSW5Ub2RuN0FhcEFlRHJMCnlEdzhOTkF6anpOcXF5T1d1c2doVk84UGM1TEhKcm9NUUhYblduc3k2UVNhclM5OXNCbXJEOU93OEdLazJFbWcKa1N3anNLZUNhM25RRjNkK2R6SFNoeTBXUTlqdWcwTkt6TVllWXhMK0VTMWdYYWRDdlVDdVIvQnNEc2lia2x5OAo2TUJZNVM4aFZrclJ5M1FkTVVNQUFUTXRRY1VUTkpQcXNkakZTNkIxaUhoRFI0eXFBdVI5R3YxQlg2OXhmUVJaCk5JWFliS0dIREtKM21wejZlQXJJT0o0bXNKUG15SlExd2pnaDRaOGd1bTkrZXp3bWwzODQ5TGhTNXh4NWJLRlcKOWhoUmV0RWhzMGw0YjJ5UEZ0eU12UTNlbmpnajhjOUs3S3E4N0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
try:
    file_content = base64.b64decode(encodedCA)
    with open("cert_file.crt", "w+") as f:
        f.write(file_content.decode("utf-8"))
except Exception as e:
    print(str(e))
    exit(1)

client = ArangoClient(
    hosts="https://c00a1fa23cef.arangodb.cloud:18529", verify_override="cert_file.crt"
)

sys_db = client.db("_system", username="root", password="KMZ4me26klgXSoiyHob7")

# Note that ArangoGraph Insights Platform runs deployments in a cluster configuration.
# To achieve the best possible availability, your client application has to handle
# connection failures by retrying operations if needed.
print("ArangoDB:", sys_db.version())